# Generated by Django 5.2 on 2025-09-16 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Firebase UID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "nombre",
                    models.CharField(blank=True, max_length=100, verbose_name="Nombre"),
                ),
                (
                    "apellido",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apellido"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="inactivo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("usuario", "Usuario"), ("admin", "Administrador")],
                        default="usuario",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "fecha_ultima_actividad",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actividad"
                    ),
                ),
                (
                    "voluntariados",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Voluntariados"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Usuario",
                "verbose_name_plural": "Estados de Usuarios",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
